# Generated by Django 5.0.6 on 2024-07-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
