# Generated by Django 5.0.6 on 2024-07-08 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0003_category_alter_addjob_options_addjob_job_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reveiw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('☆☆☆☆⭐', '☆☆☆☆⭐'), ('☆☆☆⭐⭐', '☆☆☆⭐⭐'), ('☆☆⭐⭐⭐', '☆☆⭐⭐⭐'), ('☆⭐⭐⭐⭐', '☆⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('reveiw_text', models.TextField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.addjob')),
            ],
        ),
    ]
